name:                tensor-haskell
version:             0.1.0.0
github:              "yuki-takeichi/tensor-haskell"
license:             MIT
author:              "Yuki Takeichi"
maintainer:          "example@example.com"
copyright:           "2021 Yuki Takeichi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yuki-takeichi/tensor-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - HList >= 0.5.0.0

executables:
  tensor-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tensor-haskell

tests:
  tensor-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tensor-haskell
    - doctest
